#!/usr/bin/zsh

###     Paths
filtering="Working Script.vpy"
interlaced_filtering="Interlaced Working Script.vpy"
temp="TemporaryFolder"

###     Find Video files, Begin Loop
find $1 -type f \( -name "*.mkv" -o -name "*.mp4" -o -name "*.mov" \) -print0 | while IFS= read -r -d '' video_path; do

###     File Handling
working_directory="${video_path%/*}"
filename="${video_path##*/}"
extension="${filename##*.}"
noextension="${filename%.*}"
tempname="${noextension}.mkv"
scriptname="$filtering"
problem=false

echo ""

###     Skip if already encoded
if [[ "$filename" == *-encoded.* ]]; then
    echo "-- Skipping already encoded file: $filename"
    continue
fi
if [ -f "$working_directory/$noextension-encoded.mkv" ] || [ -f "$working_directory/$noextension-encoded.mp4" ]; then
    echo "-- Encoded file already exists for: $filename"
    continue
fi

###     Determine interlacing
interlacing=$(ffprobe -v quiet -select_streams v -show_entries stream=field_order -of csv=p=0 "$video_path")

if [[ "$interlacing" != "progressive" && "$interlacing" != "tb" ]]; then
    echo "*****************************"
    echo "* Unknown interlacing type encountered: $filename"
    echo "* Interlacing type: $interlacing"
    echo "*****************************"
    continue
fi

###     Temporary folder for scenes file/filtering, etc.
mkdir $temp

###     Select our script based on interlaced detection
if [[ "$interlacing" == "tb" ]]; then
    scriptname="$interlaced_filtering"
else
    scriptname="$filtering"
fi

echo "=========================="
echo "= $working_directory/$filename"
echo "= Script: $scriptname"
echo "=========================="

###     Copy our selected script into the working directory
cp "$scriptname" "$temp/working.vpy"

###     Replace source in filtering .vpy
sed -i "11c source = r'''$(realpath "$video_path")'''" "$temp/working.vpy"

echo "= Creating lossless intermediate..."

###     Create our lossless intermediate
vspipe  "$temp/working.vpy" -p -c y4m - | ffmpeg -hide_banner -loglevel error -nostdin -y -i - -vcodec libx264 -preset faster -qp 0 "$temp/$noextension-filtered.mkv"

echo "= Beginning main encode"

###     Encode Video
av1an -e svt-av1 -v " --crf 18 --preset 2 --tune 3 --noise-norm-strength 3 --lp 12" \
    -m bestsource --verbose --force -w 16 --set-thread-affinity 8 -c mkvmerge \
    -i "$temp/$noextension-filtered.mkv" \
    -o "$temp/$noextension-encoded.mkv"

###     Run FFVship to create Metric JSONs and Graphs
FFVship -s "$temp/$noextension-encoded.mkv" -e "$temp/$noextension-filtered.mkv" -m Butteraugli --json "$temp/$noextension-butter.json"
python plot_butter.py "$temp/$noextension-butter.json" "$working_directory/$noextension-butter.png"
FFVship -s "$temp/$noextension-encoded.mkv" -e "$temp/$noextension-filtered.mkv" --json "$temp/$noextension-ssimu2.json"
python plot_ssimu2.py "$temp/$noextension-ssimu2.json" "$working_directory/$noextension-ssimu2.png"

###     Mux audio from source video with encoded video
ffmpeg -an -i "$temp/$noextension-encoded.mkv" -vn -i "$video_path" \
    -c:v copy -c:a copy \
    "$working_directory/$noextension-encoded.mkv"

###     Remove temporary folder
rm -rf $temp

done
